brace_style = "PreferSameLine"
condense_wildcard_suffixes = true
edition = "2024"
fn_call_width = 80
format_code_in_doc_comments = true
format_macro_matchers = true
#format_strings = true
hex_literal_case = "Upper"
imports_granularity = "Module"
newline_style = "Unix"
#normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
style_edition = "2024"
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = true
#wrap_comments = true
