Hide
Sleep 1s
Type "noseyparker -q scan --git-url 'https://github.com/Plazmaz/leaky-repo' && clear" Enter
Sleep 1s
Show

Sleep 1s

Type "# View findings in human-readable format with the `report` command." Sleep 0.5s Enter
Type "# This example assumes you already have a datastore from scanning at `datastore.np`." Sleep 1s Enter

Type "noseyparker report --color always | less -RS" Sleep 0.5s Enter
Sleep 5s Type "q"
