name: Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        build:
        - debian
        - alpine

        include:
        - build: debian
          dockerfile: Dockerfile
          image: ghcr.io/${{ github.repository }}

        - build: alpine
          dockerfile: Dockerfile.alpine
          image: ghcr.io/${{ github.repository }}-alpine

    name: Docker
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    # The following for multi-platform build; disabled here because it takes so long; see #39.
    #
    # The docker image built for noseyparker releases is done in the
    # `release-artifacts.yml` file.
    #
    # - uses: docker/setup-qemu-action@v2

    - uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        # Note: Caching of Docker builds within GitHub Actions is complicated to get working well.
        # It seems like the best mechanism is to use `type=registry` and use GHCR as the cache,
        # rather than trying to use `type=gha` and use GitHub Actions' cache as the cache.
        #
        # For more:
        # https://blacksmith.sh/blog/cache-is-king-a-guide-for-docker-layer-caching-in-github-actions
        cache-from: type=registry,scope=${{ matrix.dockerfile }},ref=ghcr.io/${{ github.repository }}:buildcache
        cache-to: type=registry,scope=${{ matrix.dockerfile }},mode=max,ref=ghcr.io/${{ github.repository }}:buildcache,compression=zstd

        context: .
        file: ${{ matrix.dockerfile }}
        tags: ${{ matrix.image }}:edge
        push: false
        # For multi-platform builds
        # platforms: linux/amd64,linux/arm64
        load: true
        pull: true

        labels: |
          org.opencontainers.image.title=${{ github.event.repository.name }}
          org.opencontainers.image.description=${{ github.event.repository.description }}
          org.opencontainers.image.url=${{ github.event.repository.html_url }}
          org.opencontainers.image.source=${{ github.event.repository.clone_url }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}

    - name: Test the Docker image
      run: docker run --rm "${{ matrix.image }}:edge" --version

    - name: Authenticate with GitHub Container Registry
      if: github.event_name == 'push' && github.ref_name == 'main'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push the image to `edge`
      if: github.event_name == 'push' && github.ref_name == 'main'
      run: |
        docker push "${{ matrix.image }}:edge"
